### ISSUE TITLE
How does Batch Edit behave with works

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1003]
How will Batch edit work.  Will it edit GenericFiles or will it now edit works?

**Comment by cam156** [comment]
Batch editing of the work should be configurable on what level the metadata cascades down to.
Title and a configurable list should be filtered from being editable

**Comment by hectorcorrea** [comment]
A possible outcome would be not to allow Batch Edit on works.

**Comment by hectorcorrea** [comment]
This ticket is for the planning meeting, not an implementation.

**Comment by mjgiarlo** [comment]
Working together to define a new batch editing UI is going to be a high priority in 2016. Since this issue is a high-level question, `How will Batch edit work. Will it edit GenericFiles or will it now edit works?`, I'm inclined to answer that question and close this ticket. Batch-edit will modify descriptive metadata on works in bulk.
