### ISSUE TITLE
Change Fits from a datastream into RDF

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1006]
Convert fits xml data stream into RDF properties on the GenericFile.

This is just the implementation of an existing mapping from RDF to XML.

When we characterize the file we should save the data into RDF
When view a file the characterization should come out from RDF.

**Comment by hectorcorrea** [comment]
This should include some sort of migration of the current data to the new format.

**Comment by jlhardes** [comment]
The Hydra Technical Metadata Subgroup has defined baseline technical metadata RDF properties across file types/formats: https://docs.google.com/document/d/1SZCpSIdlGfXgoYrAnW2eRKlIt6O-1ADIDDhmLrvxeLc/edit#heading=h.a8hurtypz8qi

**Comment by jlhardes** [comment]
Baseline technical metadata from the Hydra Technical Metadata Subgroup has been moved to the Duraspace wiki: https://wiki.duraspace.org/display/hydra/Technical+Metadata+Application+Profile

**Comment by mjgiarlo** [comment]
@jlhardes et al.:

Brief update: I've been going through the roughly 75 or so properties that FITS spits out, mapping them to RDF predicates.  I've pinged @kestlund over email about having the Hydra techMD subgroup's help in checking/verifying/correcting all the predicates I've suggested, since the current application profile has a small fraction of what I need for this PR.

We also discussed using this PR as an opportunity to update Sufia's dependency on an older FITS (0.6.x) to a newer one (0.8.x), and so I also updated our properties based on changes that have been made to FITS output over time.  To do this I generated a bunch of sample outputs with both versions of the tool and diffed them.  If it may be of interest, here are those sample outputs:

https://github.com/mjgiarlo/fits_output_diffs

I've also been generating vocabularies as I go and submitting them to the central rdf-vocab gem so that they are not only available to Sufia but also to the rest of the Ruby community.  You can see that work here:

https://github.com/ruby-rdf/rdf-vocab/pull/16
https://github.com/ruby-rdf/rdf-vocab/pull/18

You can see my mapping work in progress here:

https://github.com/projecthydra/sufia/commit/23f7e901f0ae9c8cede4b02a00be99ea830fef99#diff-2b453d0804db4006255b0c7d37c50742

**Comment by escowles** [comment]
We talked about this a bit in today's [metadata working group call](https://wiki.duraspace.org/display/hydra/Metadata+Call+2015-06-03), and there was some skepticism about how useful some of the FITS properties are.  Is there a subset of properties that are actually used by Sufia apps?  Are some of them acted on, or are they just displayed to the user?

**Comment by mjgiarlo** [comment]
Only a small handful (2-4), IIRC, are used in Sufia.  The rest are stored and just displayed to the user.

**Comment by mjgiarlo** [comment]
As we've seen it, characterization at point of upload is a chance to gather intel about the files in the repository. I haven't thus far been enthusiastic about dumping FITS's output because I'm not sure what all Sufia adopters' strategies are or will be for preservation (thinking here about format migration, for instance), so we have kept everything FITS spits out. It's true that a lot of this may not be useful, but I think it's also true that the cost of plopping this all into RDF in the repo is fairly low.

**Comment by escowles** [comment]
I am sympathetic to the keep-everything approach -- it will give people the flexibility to go back later and find uses for the metadata.  In theory, it would be nice to know up front what the uses will be, and to have other tech metadata sources to compare against.  We can always revisit the mapping and predicates used later on as use cases and other tools emerge.

**Comment by mjgiarlo** [comment]
:+1:

**Comment by mjgiarlo** [comment]
The current implementation maps nearly everything over from the FITS XML into RDF and discards the XML. Closing this issue.
