### ISSUE TITLE
Relative root not being appended on certain links

### ISSUE THREAD

**Issue by little9** [projecthydra/sufia#1141]
I'm running Sufia 6.0.0 in a subdirectory with Apache/Passenger and it seems like the application appends the relative root in some instances, but not in others. 

The main navigation links on the page don't include the relative root.

When uploading a file, you are redirected to an edit page that doesn't have the relative root. 

If I want to run Sufia in a subdirectory, will I need to hard code some of these links?

**Comment by jcoyne** [comment]
@little9 there are likely bugs because no one has tested this scenario before you.  When you say "main navigation links" can you confirm you are referring to the "About" "Help", "Content" links?  I suspect that these links are hard coded in the views. I'd suggest you find where these links are and use the rails url helpers to replace them. Then you can submit a pull request to fix them.

**Comment by little9** [comment]
Yeah I mean those links that are in the _controls.html.erb view. I'll submit a pull request.

**Comment by mjgiarlo** [comment]
@little9 has submitted a PR to fix this. Thanks!  Closing.
