### ISSUE TITLE
Collection without permission

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1221]
When I do not have access to see the items in a collection, the user should see in the view below a message that they do not currently have access to some of the items in the collection.

https://scholarsphere-staging.dlt.psu.edu/collections/8623j0533

![screen shot 2015-07-01 at 9 48 48 am](https://cloud.githubusercontent.com/assets/1599081/8455982/67def8b6-1fd6-11e5-9d6c-bcf17a3aa4c9.png)

**Comment by mtribone** [comment]
I think that at a minimum the user should see a message that they do not currently have access to the items or some of the items in the collection. I wonder what scenarios we would have about having access to some but not all items in a collection. And if you don't have access to all of the items, the collection should not be found via search or browsing.

**Comment by mjgiarlo** [comment]
Is the view identical when the user has access to 0 items in it and when the collection is empty? If so, perhaps we should render a message like, "The collection is empty or does not contain items to which you have access."

I don't like hiding such collections from being found. I do like providing a way for users to request access from the collection's creator.

**Comment by mtribone** [comment]
Yes the view is identical. I did think about requesting access, but in the past have heard from users that they didn't like their private collections being publicly found, since they can't make their collections private. "If all of the items in the collection are private, why does it show up in search?"

It might be worth exploring some uses cases, but I could go either way as a first step.

**Comment by jcoyne** [comment]
I can foresee users wanting to organize things into collections, but only some of the items are public. They would want that collection to be discoverable, just not the private members.

**Comment by mtribone** [comment]
Yup. I would think that if there are some public or institutional items in the collection that it would be discoverable. What about people who want the whole thing private and "hand out" access? I don't know how large of a request this is for users, but have had some ask about it in the past. 

I can get behind requesting access as a first step.

**Comment by mjgiarlo** [comment]
Hmm, maybe we should allow collections to use the same access controls as GFs, then.  We already have a widget that works for GFs...

**Comment by mtribone** [comment]
It could be useful. In the meantime the "The collection is empty or does not contain items to which you have access." message and an opportunity to request access seems like a short putt.

**Comment by mjgiarlo** [comment]
I'm not sure requesting access is less work than tweaking the access controls widget. It'd be good to hear from e.g. @cam156 @jcoyne @awead @hectorcorrea on that one.

**Comment by awead** [comment]
I'm for giving Collections the same access controls as GFs. It keeps it simpler. My feelings are:

* hide files for which you do not have read access, with an optional message perhaps
* list names of files for which you have discover access, similar to catalog index views
* display collections even if there are no accessible files within them

Yeah, some of the points are a bit odd, but this keeps it consistent with what happens when you search for files given these access control restrictions.

**Comment by mjgiarlo** [comment]
Refocusing this ticket on:

> When I do not have access to see the items in a collection, the user should see in the view below a message that they do not currently have access to some of the items in the collection.

Broader work to add access controls to collections should be ticketed separately. Moved to 7.0.0 milestone.
