### ISSUE TITLE
Metadata is not being saved during upload

### ISSUE THREAD

**Issue by tworrall** [projecthydra/sufia#1315]
When uploading a file in versions 6.2 and 6.3, metadata that gets entered on the form is not being saved. I've tried this in vanilla Sufia instances, specifying a new title and adding keywords. The new title does not appear on the dashboard, and when I go back to edit the file, the keywords are not there. There are no problems with the edit form, which works as expected.

Add metadata during upload -
![screen shot 2015-09-15 at 10 42 17 am](https://cloud.githubusercontent.com/assets/2678027/9879712/942dd742-5b96-11e5-97c7-77656470f508.png)

After saving - 
![screen shot 2015-09-15 at 10 42 38 am](https://cloud.githubusercontent.com/assets/2678027/9879730/a6cffa2e-5b96-11e5-99ee-10054d670fe5.png)

Editing the newly added file -
![screen shot 2015-09-15 at 10 43 15 am](https://cloud.githubusercontent.com/assets/2678027/9879745/b6c085f2-5b96-11e5-8625-869e428e838d.png)

**Comment by mjgiarlo** [comment]
I wonder if background jobs aren't running.

**Comment by tworrall** [comment]
Redis is running:
redis-cli ping
PONG

And I've spawned Resque's workers:
QUEUE=* rake environment resque:work

**Comment by mjgiarlo** [comment]
@tworrall Does the little clock next to this checkbox ever go away? https://cloud.githubusercontent.com/assets/2678027/9879730/a6cffa2e-5b96-11e5-99ee-10054d670fe5.png

If not, that's likely because the batch update job is never processed. Can you share a snippet showing what all is in your running Redis instance? You can drop into `redis-cli` and issues the following command: `keys *`

**Comment by tworrall** [comment]
Mike,

The clock does not go away. Here's the snippet you asked for:

 1) "sufia:development:workers"
 2) "sufia:development:worker:lib-dev-030.serverfarm.cornell.edu:5491:*:started"
 3) "events:1"
 4) "events:2"
 5) "resque:queue:characterize"
 6) "resque:queue:audit"
 7) "GenericFile:bc386j20b:event"
 8) "sufia:development:queues"
 9) "resque:queues"
10) "events:latest_id"
11) "sufia:development:stat:failed"
12) "sufia:development:stat:failed:lib-dev-030.serverfarm.cornell.edu:5491:*"
13) "sufia:development:stat:processed"
14) "User:tlw72@cornell-dot-edu:event:profile"
15) "sufia:development:stat:processed:lib-dev-030.serverfarm.cornell.edu:5491:*"
16) "resque:queue:event"
17) "resque:queue:batch_update"
18) "sufia:development:failed"
19) "GenericFile:1c18df763:event"

I take it this is something that you can't reproduce?

Thanks,
Tim

**Comment by mjgiarlo** [comment]
@tworrall I can't reproduce it but I have seen this behavior before. It was reported in #1131 and fixed by #1137. Before we go tinkering in Sufia's code, can you see if spinning up resque-pool fixes this? See the instructions here: https://github.com/projecthydra/sufia#start-background-workers

**Comment by rotated8** [comment]
If you can view the Resque front end (either by [Sufia's instructions](https://github.com/projecthydra/sufia#view-resque-jobs), or [Resque's](https://github.com/resque/resque/blob/1-x-stable/README.markdown#rails-3)), you can confirm the number of workers.

**Comment by mjgiarlo** [comment]
@rotated8 I believe what @tworrall is seeing is because of the namespacing issues fixed by #1137. If you look at the Redis output above, you will see that the workers are in the `sufia:development` namespace, meanwhile the queues are in the `resque` namespace, which means that workers will never see those queues. This has been fixed in Sufia since 6.1.0, but I was speculating that perhaps the fix only works when workers are managed via resque-pool and we may have neglecting to test/fix behavior when using the rake task. (I have never used that rake task; I've always reached for resque-pool.)

That said, the front-end tools are helpful to know about, so thanks!

**Comment by jcoyne** [comment]
Try this take task: 'QUEUE=* rake environment resque:work' If you don't load the environment task it works on the default NS

**Comment by tworrall** [comment]
The description of #1137 led me to the answer. The redis_config file did not have the Resque.redis.namespace line that was added as part of that fix. This was in the 6.2 (now 6.3) app that was originally at 6.0. 

Thanks for all the help.
