### ISSUE TITLE
geonames username should be configurable

### ISSUE THREAD

**Issue by tonmoy18** [projecthydra/sufia#1336]
The username used with geonames api is hard coded into the sufia-model. Someone using the sufia gem cannot change it easily.
The api username should be configurable for other applications who are using the sufia gem.

**Comment by mjgiarlo** [comment]
@cam156 does this ring a bell?

Sounds like a :+1: to me.

**Comment by cam156** [comment]
@mjgiarlo I was thinking we would want to change to questioning authority, vs more customizations, but I would think a configurable user name would be a small change that would be helpful in the interim. :+1:

**Comment by mjgiarlo** [comment]
Great, @cam156! Are you inclined to put in a PR, @tonmoy18?

**Comment by mjgiarlo** [comment]
(Oops, sorry to have closed the issue. Mistake. Re-opened now.)

**Comment by tonmoy18** [comment]
Sure, I will create a PR when I can

**Comment by mjgiarlo** [comment]
@tonmoy18 Excellent. Have you submitted a contributor license agreement yet? (Sorry, sometimes it's not clear to me how to map GitHub usernames onto the names we have listed in our CLA list!)

**Comment by tonmoy18** [comment]
No, sorry I have not done that yet.

**Comment by mjgiarlo** [comment]
@tonmoy18 OK. Are you familiar with this process, or would it be helpful if I went over it briefly?

**Comment by tonmoy18** [comment]
I am not familiar with the process. If you could help me it would be great.

**Comment by mjgiarlo** [comment]
@tonmoy18 OK. May I ask who you work for? The process is different depending on if you're already covered by a corporate CLA, a number of which we already have on file.

**Comment by tonmoy18** [comment]
I work for VirginiaTech University Libraries. We are using sufia for the new VTechData under development.

**Comment by mjgiarlo** [comment]
OK, great, @tonmoy18. Then you are covered by VT's corporate CLA, and you only need to submit an individual CLA. You can read more about [our CLA processes](https://wiki.duraspace.org/display/hydra/Hydra+Project+Intellectual+Property+Licensing+and+Ownership).

The process itself is fairly simple -- you just need to print out the [Hydra Project iCLA](https://wiki.duraspace.org/download/attachments/31662457/Hydra%20Project%20Contributor%20License%20Agreement%20for%20Individuals-20121216.pdf?version=1&modificationDate=1355704453858&api=v2), fill it out and sign it, and then send it to legal@projecthydra.org. (I'm guessing @rotated8 @yinlinchen and @tingtingjh can help too since they have already been through this process.) Let me know if you have any questions about this process, and I'd be happy to help.

**Comment by tonmoy18** [comment]
Thank you. I will do it as soon as I can.

**Comment by mjgiarlo** [comment]
Much obliged, @tonmoy18

**Comment by tonmoy18** [comment]
Hi, I have already created a pull request. I did not write any documentation about it. Should I write a paragraph about the geonames username on the repository wiki on this page: https://github.com/projecthydra/sufia/wiki/Domain-Terms-tables ?

**Comment by mjgiarlo** [comment]
@tonmoy18 I don't think that will be necessary, but thanks. Someone (perhaps myself) will be reviewing your PR soon
