### ISSUE TITLE
Add a test for My Files Controller to make sure we are not getting files we do not have edit permission to

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1343]
Noticed there was no test that made sure we had edit access to all files in MyFilesController.

The MySharesController test includes one here: https://github.com/projecthydra/sufia/blob/master/spec/controllers/my/shares_controller_spec.rb#L75

**Comment by awead** [comment]
@cam156 It's only going to show works that the user themselves have deposited and because of paranoid permissions, depositors must have edit access. Here are the cases covered in the test:
https://github.com/projecthydra/sufia/blob/master/spec/controllers/my/files_controller_spec.rb#L64-L74
I'm trying to think of a test case, but can't come up with one.

**Comment by cam156** [comment]
@awead Looks like I already fixed this and just forgot to close it...
