### ISSUE TITLE
Uploading from work does not add file to work

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#1415]

**Comment by grosscol** [comment]
@awead noticed that when uploading a file, there was not a work to attach it to.  However, when `generic_work#new` is called, the `curation_concern` is a work, but it has not been persisted. The work's id is nil.  I think this is what was causing the observation that the work had not been created.

So what is happening now, is that a work exists when `generic_work#new` is called and another one is created after the file is uploaded.  I think the fix for this is to pass the work and not work.id.  That should avoid the logic that creates a work if one does not exist.

**Comment by awead** [comment]
@grosscol from what page are you uploading?

**Comment by grosscol** [comment]
generic_works/new
