### ISSUE TITLE
Regression: Batch edit functionality

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1461]
Compare https://github.com/projecthydra/sufia/blob/6.x-stable/app/views/my/_sort_and_per_page.html.erb with https://github.com/projecthydra/sufia/blob/master/app/views/my/_sort_and_per_page.html.erb

"Edit Selected" and `batch_delete` are gone now.  We want this functionality to work like it did in 6.0

**Comment by jcoyne** [comment]
I'm not sure why this is closed, it's still not working like it did in 6.0.

**Comment by njaffer** [comment]
So when I compare, Sufia 6 and the master branch, I cannot get the document info from solr, the reason is that it is saved as GenericWork and not FileSet

Should this be GenericWork instead of FileSet? Any thoughts?https://github.com/projecthydra/sufia/blob/master/app/controllers/concerns/sufia/batch_edits_controller_behavior.rb#L23

**Comment by mjgiarlo** [comment]
@njaffer Yes, I believe so.

**Comment by njaffer** [comment]
Ok, I changed it and I am getting the information but now the error is the default render form, it is rendering curation concerns edit form and not the batch edit form in sufia. Because of this I am getting an error on this line: https://github.com/projecthydra-labs/curation_concerns/blob/64eab4d87fac8b88367ebb5e34b4d34ad7ce6716/app/views/curation_concerns/base/edit.html.erb#L1

Any ideas?

**Comment by mjgiarlo** [comment]
@njaffer I wonder if the `BatchEditsControllerBehavior` module is finding the CC view before the Sufia view because of this method: https://github.com/projecthydra/sufia/blob/master/app/controllers/concerns/sufia/batch_edits_controller_behavior.rb#L65-L68

I haven't analyzed this deeply yet, but I wonder if that method should return `@_prefixes ||= super + ['curation_concerns/base']` instead, so that Sufia views are found before CC ones. @jcoyne added this code so he may have a better suggestion.

**Comment by njaffer** [comment]
@mjgiarlo , it worked! Thank you..

**Comment by mjgiarlo** [comment]
@njaffer :clap:
