### ISSUE TITLE
Refactor test suite to remove uses of allow_any_instance_of

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1617]
Robobop 37.2 complains vociferously about the use of `allow_any_instance_of` and `expect_any_instance_of`. However, it is used pretty thoroughly in the codebase. We should take some time to refactor our tests so that we don't use it anymore. For now, it has been added to the list of exclusions in `robocop.yml`.

**Comment by mjgiarlo** [comment]
:+1: to adding it to the list of exclusions for now. Thanks, @awead

**Comment by atz** [comment]
`allow_any_instance_of` leads to bad logic.  If you are stubbing something you should be guaranteeing that the stub actually gets used (via `expect`), or you didn't need to stub it in the first place.  It is also exceedingly valuable to catch that rather than being called once, your stub is called, say **8** times... whilst meanwhile you were wondering why your app was so slow.

**Comment by awead** [comment]
Agreed. I would welcome any PRs you have that can further this effort! :smile:

**Comment by mjgiarlo** [comment]
I can't foresee a day when any of us will have the time and inclination to do this work in Sufia. Closing for now. `.rubocop_todo.yml` is always there if anyone wants to take a hack at it. :)
