### ISSUE TITLE
Jobs for user messaging instead of services

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#1659]
### Descriptive summary

I've noticed that we use jobs to log user and file events (via Redis), for example `EventJob`, but we use services for sending users messages, ex. `Sufia::MessageUserService`. I'm wondering if we might want to use jobs instead, or if there was a reason to use a service.

The service is called immediately, whereas the job is done async. so maybe that's the explanation.

**Comment by mjgiarlo** [comment]
Events don't need to be in jobs; they *could* be run synchronously, because Redis is :rocket:. If the services were sluggish, I'd be happy for them to be converted to jobs. 'Til then... `¯\_(ツ)_/¯`

Good :eyes:, and thanks for raising this.

**Comment by awead** [comment]
Yeah, either way... all services or all jobs. Just thought there should be consistency.

**Comment by mjgiarlo** [comment]
After seeing #2512, I wondered if it were an opportunity to revisit this issue (if someone has the :bike:). If so, I might like to see our pattern here follow this principle: jobs should be a lightweight layer over other code (*i.e.*, we should endeavor to keep original code outside of jobs so that folks have a choice of whether or not to jobify an operation.). One possible outcome of this work, then, would be for the existing event job code to move into service objects, and the existing job classes would simply call the new service objects. I'd like feedback on this pattern from @projecthydra/sufia-code-reviewers @tpendragon @jeremyf and other interested parties.
