### ISSUE TITLE
Re-style GenericWork show page

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1722]
Re-style the `GenericWork` show page per the [Sufia UI WG wireframe](https://wiki.duraspace.org/x/DAF6B).

See the following [comment](https://github.com/projecthydra/sufia/issues/1722#issuecomment-209572261) re: the scope of this ticket.

**Comment by elrayle** [comment]
The wireframe in jcoyne's comment is out of date.  The new wireframe is partially complete and is located at https://wiki.duraspace.org/x/DAF6B.  This wireframe shows the default state as a full page wireframe.  There are partial page wireframes farther down the page that shows variants for sections on the page.  It is the variants that are not complete.

**Comment by mjgiarlo** [comment]
@cbeer I see this issue listed as in progress. Are you actively working on this one? (Doing some issue tidying.)

**Comment by cbeer** [comment]
It was my intent -- I ended up blocked on whether this work belongs in Sufia or curation_concerns. I'll give it back to the pool in case someone knows better.

**Comment by elrayle** [comment]
All the variants are in the wireframe at:  https://wiki.duraspace.org/x/DAF6B
Notes describing behaviors are to the right of each wireframe and variant.

**Comment by elrayle** [comment]
@jcoyne asked the following question in the wiki.

> "How about a variant with a video, audio, or large image (zoomable player) file selected as the representative_media?"

Several issues are involved in this.  All were pushed to 7.1 in order to complete the design process for 7.0 in a more timely manner. 

1. Selection of a thumbnail by selecting one of the items in the work as representative.  Requires enhancements to the New/Edit Work designs.  Current thumbnail selection for 7.0 was envisioned to be first uploaded document's thumbnail.  And in 7.1, there will be a selection process.
2. Adding an image for the sole purpose of serving as a thumbnail for the work that is not an item's thumbnail.  It was unclear whether this was a use case that should be supported.  It was seen as new functionality.
3. Preview of items on Show Work page.  The 'eye' icon beside each item should launch a content appropriate previewer.  The UI Working Group did not fully define what this means.  The thumbnail for the items are clearly too small to use to stream a video.  Part of the challenge in defining this is that different browsers have different default behaviors.  For example, if I preview a pdf in Safari, the pdf is downloaded.  If I preview it in Chrome or Firefox, it is displayed in a new tab in the browser.
4. Preview of work based on work thumbnail.  We discussed the desire to have the representative thumbnail for the work acting similar to File thumbnail's in Sufia 6.  This is only meaningful when the user is able to select which item is the representative thumbnail.

**Comment by jcoyne** [comment]
@elrayle Hector already did the the first point in this commit: https://github.com/projecthydra/sufia/commit/224f02f7280b85fed8f1eea2c6066153527f2bff

**Comment by jcoyne** [comment]
@elrayle for \#2 the point of a thumbnail that is not the primary media is mostly when you have a video or audio file.  The thumbnail could be a scan of the cover.

**Comment by mjgiarlo** [comment]
@jcoyne Should we discuss this ticket and decompose it into smaller tickets in a Hangout today, like we did for the other biggish UI tickets?

**Comment by mjgiarlo** [comment]
Chatted with @jcoyne today and we came up with the following proposal to take up the work in this ticket:

1. Re-organize the existing `GenericWork` show page to arrange *existing* UI elements such that they display as specified in the [Sufia UI WG wireframe](https://wiki.duraspace.org/x/DAF6B).
1. Analyze the deltas between that and the wireframe, and ticket the deltas separately.
