### ISSUE TITLE
Update to latest CC to pick up single-use links in the UI

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1750]
Single-use links are no longer exposed in the UI. Blocked by https://github.com/projecthydra-labs/curation_concerns/issues/278

Once https://github.com/projecthydra-labs/curation_concerns/issues/278 is closed, first, clean up the following vestigial bits of single-use links:

- [ ] https://github.com/projecthydra/sufia/blob/master/app/assets/javascripts/sufia/single_use_link.js
- [ ] https://github.com/projecthydra/sufia/blob/master/app/assets/javascripts/sufia.js#L39
- [ ] https://github.com/projecthydra/sufia/blob/master/sufia.gemspec#L48
- [ ] https://github.com/projecthydra/sufia/blob/master/lib/sufia/engine.rb#L8
- [ ] https://github.com/projecthydra/sufia/blob/master/lib/sufia/engine.rb#L57
- [ ] https://github.com/projecthydra/sufia/blob/master/spec/javascripts/single_use_link_spec.js.coffee
- [ ] https://github.com/projecthydra/sufia/blob/master/app/views/collections/_show_document_list_menu.html.erb#L5-L9
- [ ] https://github.com/projecthydra/sufia/blob/master/app/views/collections/_action_menu.html.erb#L7-L10 (or do we need this override :question:)
- [ ] https://github.com/projecthydra/sufia/blob/master/app/views/my/_action_menu.html.erb#L8-L11 (or do we need this override :question:)

Then point Sufia at the latest CC to pick this up and test/verify that this works per the following acceptance criteria:

1. Single-use links are exposed in the UI for `FileSets` only (not for `GenericWorks` or other curation concerns).
1. Only one single-use link is generated for each `FileSet` and it allows *download* access to the `original_file` within the `FileSet` (the binary content, not a splash page).
1. Clicking the single-use link button for a `FileSet` pops up a (Bootstrap) modal showing the single-use link, highlighted, with a GitHub-like "copy me" button beside it.

**Comment by hectorcorrea** [comment]
We decided that the fix for this should go in CurationConcerns since that's where most of the functionality resides anyway. It should relatively easily to add the work in PR #1828 to CC.

We also decided that to keep things simple we are going to allow users to use the Single-Use link at the FileSet level (on each file) rather than at the work level.

Lastly, for version 7.0.0 we are going to keep the UI similar to Sufia 6 in which we will pop-up a window to the user with the link to **download** the file rather than the current Sufia 7 workflow in which users go to a different page. If we could we should also make the process of copying the link to the users' clipboard easy (e.g. with a copy to clipboard button or at least highlighting the link)

**Comment by mjgiarlo** [comment]
Discussed on 4/13 and resolved the following:

1. This ticket should be implemented in CurationConcerns rather than Sufia.
1. Single-use links will be exposed in the UI for `FileSets` only (not for `GenericWorks` or other curation concerns).
1. Only one single-use link will be generated for each `FileSet`, allowing download access to the `original_file` within the `FileSet`.
1. Clicking the single-use link button for a `FileSet` should not redirect to a new view, but rather it should pop up a (Bootstrap) modal showing the single-use link, highlighted, with a GitHub-like "copy me" button beside it.

(Sorry, @hectorcorrea, I was 90% done with this when I saw your comment come in! :laughing:)

**Comment by mjgiarlo** [comment]
Single-use links are already implemented in CC and Sufia. Closing.
