### ISSUE TITLE
when screen is a large width, seach field gets small

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1875]
<img width="1153" alt="screen shot 2016-04-15 at 11 15 36 am" src="https://cloud.githubusercontent.com/assets/92044/14567814/781f8322-02fb-11e6-8d76-d1e1a4b87437.png">

It looks okay at a medium width.

**Comment by atz** [comment]
If I remove the `col-md-3` from the innermost element and just let it scale with the parent `col-xs-6 col-md-5 col-lg-6` column, it seems more correct at all sizes.  It is the only thing in the parent anyway.

**Comment by atz** [comment]
Also, why do have a `_search_collection_dashboard_form.html.erb`, then not use it on the collection edit page?

Instead of:
![screen shot 2016-04-18 at 2 48 10 pm](https://cloud.githubusercontent.com/assets/109954/14620979/ab8a0b44-0574-11e6-8917-f63e5dab8f8b.png)

We have:
![screen shot 2016-04-18 at 2 48 23 pm](https://cloud.githubusercontent.com/assets/109954/14620981/ad2038e8-0574-11e6-8a52-82616cb741c3.png)

And instead of styling in-row with the H2 ("Manage Items in this Collection"), it bumps to underneath it at all sizes.  Searchbox has a fixed 30-char width which is similarly annoyingly small even when space is ample.
