### ISSUE TITLE
Pushing "return" on file upload page creates a work

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1891]
Even if files haven't been uploaded.

The validation javascript should block form submission if no files are uploaded

**Comment by atz** [comment]
Having trouble reproducing this.  

Example page:
http://localhost:3000/concern/generic_works/new#files

Return doesn't trigger anything, even after adding title and checking deposit agreement box.  Or after adding files even.  

The "add files" button and the save button are in different forms and the save button only gets hit by "return" if that form has focus.  So if I drag/drop files over most of the document, the focus isn't on the save form.  If I use the "add files" button, return only retriggers the same button.

Notably, saving works seems busted anyway, when I do get everything lined up, the save button yields:
```
ActiveFedora::UnknownAttributeError at /concern/generic_works
unknown attribute 'remote_files' for GenericWork.
```

**Comment by atz** [comment]
I am on OSX/chrome, if that matters.

**Comment by jcoyne** [comment]
I'm pretty sure this is an ActiveSupport::Autoload bug having to do with load order. I've been able to solve it every time by restarting the dev server.

**Comment by jcoyne** [comment]
The original bug with the "return" button is reproducible on Firefox.

**Comment by hectorcorrea** [comment]
yup...I can reproduce this in FireFox.

**Comment by hectorcorrea** [comment]
I was not able to fix this one. What I figured was that when the page is first loaded this method executed which runs the `sufiaUploader()` function:

https://github.com/projecthydra/sufia/blob/master/app/assets/javascripts/sufia/fileupload.js#L5

The definition of the `sufiaUploader()` function is this:

https://github.com/projecthydra/sufia/blob/master/app/assets/javascripts/sufia/uploader.js#L23

The `sufiaUploader()` function just wires up where the uploader will POST the files.

What I didn't get to was how to add a before event so that it does not execute the actual upload unless the validations pass.

I am going to unassign me from this ticket from now.

**Comment by jcoyne** [comment]
I have not been able to duplicate this now. Closing.

**Comment by jcoyne** [comment]
Okay, If you tab over to the "visibility" button and then press enter it will submit.
