### ISSUE TITLE
'Share Work' feature not working

### ISSUE THREAD

**Issue by njaffer** [projecthydra/sufia#1973]
### Descriptive summary

Current Sufia 7 master branch,As User A I tried to create a new work and  shared it with User B. When I logged in as User B, I don't see any notification, nor see the work in 'Files Shared with Me' 

### Expected behavior

As User B, I get notification and I can see the work shared with me.

### Steps to reproduce the behavior

1. Create a new Work
2. Share work with 'Edit' Access
3. Save the Work
4. If you get the error "unknown attribute remote_files", restart the app!

### Related work

None

**Comment by njaffer** [comment]
It is working, but you have to click on + button to save it!. The + button seems to be confusing as 'Add More' button
<img width="737" alt="screen shot 2016-05-05 at 10 04 52 am" src="https://cloud.githubusercontent.com/assets/12487929/15045516/e69ba238-12a8-11e6-9648-68c7007a6d92.png">

**Comment by mjgiarlo** [comment]
Advice on the above, @projecthydra/sufia-ui-ux-advisors :question:

**Comment by mtribone** [comment]
My initial thoughts are that the steps could be a little more explicit, so that people understand that you need to 1) select user 2) choose access 3) finish or add or share instead of the confusing + button. And then you get feedback when complete.

**Comment by newmanld** [comment]
I think on the wireframe we had '+ Add' as the button, not just a plus sign  - does this better cue the user that they need to click on the button to save?  Alternatively should it say '+ Save'?  Then once saved, the  button would meant to change to a  '-Remove' (or similar) button - with another row below it populated to be able to share the work with additional users?   (Same with groups)  

The difficulty here is having two fields - 'search for a user' and 'choose access' so I guess we need a button to complete the task.   The options under 'Choose Access' are Edit and View?  I suppose this could be pulled apart but it would make the form lengthier.

**Comment by newmanld** [comment]
Additionally it might help to highlight the action to have a background color behind the +Add - although maybe this has implications for consistency of styles of buttons elsewhere. 
![addbutton](https://cloud.githubusercontent.com/assets/3521707/15050056/8c287ed6-12bf-11e6-95cb-cad437937656.jpg)

**Comment by mtribone** [comment]
@newmanld Matching the other +Add buttons would at least make it consistent, which is where I think that we were going with the wireframes. But yeah agree that the +Add is a good start instead of the plus sign

**Comment by mtribone** [comment]
I also think the gap between the add user and choose access creates some issues, too. Might appear that you only need to select the user and poof you're done–kinda like how transfers work. It's inconsistent and confusing.

**Comment by newmanld** [comment]
Agree with @mtribone.  I think it would also be consistent with the wireframe to make the 'search for a user' field the same width as 'Select a Group'.

**Comment by atz** [comment]
There are also other buttons with just a plus, so you can pick which part you prefer to be consistent with.  The "add similar row" functionality is fine and not really the issue here.  IIUC, the primary issue is (or was) the form doesn't save data without adding an empty row.

**Comment by mtribone** [comment]
@atz If I understand @njaffer comment above "The + button seems to be confusing as 'Add More' button". She didn't find the work shared with her as User B because she never clicked the + button to add User B. There are definitely gaps in the consistency of the interface by putting together CC and Sufia in addition to the UI Working Group only getting the workflow for works done. @mjgiarlo asked so that's why we're saying that we prefer +Add. It would be good to work through the interface and point out the inconsistencies.

**Comment by sfbetz** [comment]
I think the problem is that there is one button standing in for two actions. 
+ should only add new rows to the interface to add new users. I don't think relabelling it +Add will do much to signal to the user that they're actually sharing when they click the button.
My suggestion would be to add a "share" action button (at bottom right) that saves the selection.
