### ISSUE TITLE
BatchEdit is not destructive

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2303]
### Descriptive summary
If all files in the batch have a contributor of "Bob" and you edit the batch, remove Bob and then save, I would expect that bob would not be a contributor on any files. However, presently "Bob" is not removed as a contributor from any of the files.

**Comment by mjgiarlo** [comment]
Thoughts on this, @sufia-ui-ux-advisors?

**Comment by jcoyne** [comment]
We need to be careful with this fix. Because currently the batch edit only shows values that are common to all of the batch items.  So we need to make sure that "Rhonda" isn't removed as a contributor if she was only present on 1 out of 3 works in the batch.

**Comment by hackmastera** [comment]
My experience of batch edit in sufia 6 was that it has so many problems. see, e.g., https://github.com/chemheritage/chf-sufia/issues/67#issuecomment-185339085

**Comment by hackmastera** [comment]
If what Justin is saying is true, that it only shows common values, then that is a huge improvement!

**Comment by jcoyne** [comment]
@hackmastera you are correct and I was wrong. https://github.com/projecthydra/sufia/blob/master/app/forms/sufia/forms/batch_edit_form.rb#L29-L38

**Comment by hackmastera** [comment]
@jcoyne bummer!!

Well, i'm not sure what kind of thoughts @mjgiarlo is looking for but I favor a complete rewrite / redesign of batch edit. Which seems entirely out of scope for this issue. I drew a whiteboard sketch a hundred years ago and am trying to dig it up.

@atz suggested renaming the functionality to 'metadata normalizer' [1] which is a great name but I think users need better functionality here and it would be better to flesh out batch edit to really work.

[1] https://github.com/chemheritage/chf-sufia/issues/67#issuecomment-229148475

**Comment by jcoyne** [comment]
I think it would be super if you wanted to redesign the batch edit. 👍

**Comment by mjgiarlo** [comment]
tbh, my druthers are to leave batch-edit as is (barring major bugs) until we have time to redesign it from the ground up.

**Comment by atz** [comment]
Actual "Batch Edit" functionality, which for clarity here we mean "Edit operation(s) serially applied to an arbitrary set of records" is a major feature of considerable importance to prospective users (probably even more so to legacy users who may need to massage their data during and after migration).  It is also a gnarly can of worms with guaranteed feature creep as soon as it contacts real users and real data.  The existing normalizing approach may serve a complementary role, but I doubt it has any durable value as a stand-in for true batch editing.  

The design would have to abstractly represent edit operations, so given our data, the potential complexity is daunting. Remove (ALL) matching values vs. remove ONE matching value (a duplicate), for example.  

Would love to see your whiteboard design, @hackmastera.  That being said, I don't know what to say about this ticket.  Seems like a "WONTFIX" or "delete buggy feature".  Anecdotally, the feature received little use, so maybe removal/deferral is acceptable.

**Comment by hackmastera** [comment]
Well i would love to see it too. I am thinking this must be one of the photos I lost when my then-two-year-old deleted everything on my phone by entering the wrong passcode too many times in a row. It's not enough to lock your phones, people! I give up.

**Comment by awead** [comment]
I think for Sufia 7 greenfield adopters, there won't be much use for this feature, other than perhaps for administrative use cases where you need to apply a set of changes to a group of works, such as marking a bunch "private" because of some changes in policy. Penn State has had this need in the past.

The history of batch edit has to do with previous versions of Sufia that didn't have works. In some cases, a user would upload a batch of files that were all related somehow. In fact, that's what the actual Batch object was intended to do. However, since each uploaded file became its own GenericWork, the only way to apply changes to all the files (after the initial upload) was to regroup them again in a batch and edit.

Now that Sufia 7 uses works, it _seems_ less likely that a user would batch create works, as opposed to uploading multiple files within one work. Of course, the jury's still out on that and it remains to be seen. There's an option to batch create new works, so there's going to be a need to batch edit them as well.

For now, I agree with @mjgiarlo that batch edit should be left alone until we see how users are going to utilize it, and based on that feedback, push it the indicated direction.

Looking ahead to migration, I can see a need for batch edit that prepares works for merging. This would something pre-7 Sufias might want to do whereby old GenericFile objects that were migrated to GenericWorks could be combined in a single GenericWork, and all of its files moved into file sets. This would close the loop on the original use case I outlined above when a user uploads a batch of files that they always intended to be together, but never could explicitly do that because of the limitations of GenericFile.

**Comment by cam156** [comment]
@jcoyne I just testing this on our sufia 6 instance and it used to delete a contributor.  This seems like a bug that has been introduced by the migrations.  

I would love to see an overhaul of batch edit.  When we talked about it in the past we had said that a spread sheet type editor with the ability to see all the columns and values and copy down (across) to all records would be nice.

**Comment by cam156** [comment]
I just tested destruction of a creator and that seems to work. @jcoyne can you verify that the bug you noted still exists?

**Comment by jcoyne** [comment]
Yea, seems to work now.  Closing.
