### ISSUE TITLE
default message talks about background

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2395]
### Descriptive summary
Sufia 7.0 by default runs processes in the foreground, so why does the default message talk about background jobs?

I would expect the default message to either see if the jobs are configured and change, or just tell the user there file has been uploaded...

![screen shot 2016-08-05 at 11 54 44 am](https://cloud.githubusercontent.com/assets/1599081/17442411/9e5b3fc6-5b03-11e6-800a-1e54de252a25.png)

**Comment by mjgiarlo** [comment]
Good catch, @cam156!

**Comment by jcoyne** [comment]
You *should* be running it in the background in production.  It runs in the foreground only for convenience in development and testing.

**Comment by jcoyne** [comment]
but using the term "background" is jargon and should probably be avoided.

**Comment by mjgiarlo** [comment]
@jcoyne I took @cam156's point to be that if you don't configure background jobs, the flash message lies to you because the "jobs" have already run. There are two potential problems here:

1. People could be running in production without background jobs configured.
2. Devs who are kicking the tires, running the app in the dev environment, are misled that background jobs are running even though they never set one up.

Does that sound right, @cam156?

Problem 1 seems to be orthogonal to this ticket, and more educational than anything else. Problem 2 could be solved with some logic that asks AJ about how it's configured and chooses an appropriate flash message. The discussion I think we should have is whether problem 2 is worth fixing.

**Comment by cam156** [comment]
@mjgiarlo seems right.   @jcoyne Maybe there is no need to fix it based on the fact that the jobs should always be running.

**Comment by mjgiarlo** [comment]
@cam156 OK! should we close the ticket or rework it or whaddya think?

**Comment by cam156** [comment]
@mjgiarlo We can close it, but I am not sure how we are going to educate people that the default behavior is one you should never be using in production... Especially for Sufia 6 users who by default had background jobs before.  Having the default imply jobs are running seems confusing, unless we are also outputting warning messages or something letting the user know the default configuration is bogus.

**Comment by mjgiarlo** [comment]
@cam156 The Sufia README does link here: https://github.com/projecthydra/sufia/wiki/Sufia-Management-Guide#background-workers. That's something, anyway.
