### ISSUE TITLE
When creating a work I can choose anyone's collection

### ISSUE THREAD

**Issue by cam156** [projecthydra/sufia#2407]
### Descriptive summary

In sufia 7 when I create a work I get a listing of everyone's collections including ones I do not have access to in the relationships tab.

### Expected behavior

I should see only collections I have edit access to.

### Actual behavior

My Collections
![screen shot 2016-08-08 at 10 56 08 am](https://cloud.githubusercontent.com/assets/1599081/17489736/9317caa0-5d6d-11e6-9b31-9c57389afa7f.png)

I see everyone's collections
![screen shot 2016-08-08 at 10 55 53 am](https://cloud.githubusercontent.com/assets/1599081/17489745/9c74bd60-5d6d-11e6-95db-8a05c5b797d5.png)

**Comment by atz** [comment]
Seems to be populated by `available_collections(nil)`, a method that appears only that one time in Sufia.  It comes from curation concerns here:
https://github.com/projecthydra/curation_concerns/blob/89c3c702b70754e63a6c322bcd9d53bffb4e4a1e/app/helpers/curation_concerns/collections_helper.rb#L34

Somewhere in this chain seems like a good place to accept a block argument for filtering the collections.

**Comment by atz** [comment]
Looks like CC anticipates user-related filtering be implemented on the user via a `collections` method, as here:
https://github.com/projecthydra/curation_concerns/blob/89c3c702b70754e63a6c322bcd9d53bffb4e4a1e/app/helpers/curation_concerns/collections_helper.rb#L49

**Comment by atz** [comment]
Our generated user injects:
- `Hydra::User`
- `CurationConcerns::User`
- `Sufia::User`
 
Which one is the right level to implement this?

**Comment by atz** [comment]
Discussion on slack offered possible implementation directions for `user_1.collections`:
- Use a `Blacklight::SearchHelper`  search builder to filter solr params
- Using CanCan via `Sufia::Ability` -- not something you can query for 

There already is a `Sufia::MyCollectionsSearchBuilder` builder class [here](https://github.com/projecthydra/sufia/blob/master/app/search_builders/sufia/my_collections_search_builder.rb) which seems like it would help.  It answers the question "in which collections am I a depositor?", not "**to which collections may I deposit?**"... But is that really as sophisticated as Sufia is going to get about it?  

A site in production with hundreds of depositors and hundreds of collections, tens of thousands of items, when they hire each new archivist, they are supposed to manually add them to dozens of collections relevant to their work?  And then re-add all the current archivists to each relevant new collection?  That is a recipe for security failure.

The idea of chaining solr params and aggregating `fq` clauses is apt, but the code for this approach is pretty circuitous.  For `MyCollectionsSearchBuilder`, we use 5 mixins from 3 different engines to build our own base class and mixin, a lineage involving a dozen ancestors including ActiveFedora... all just to get:
```
_query_:"{!field f=has_model_ssim}Collection" AND _query_:"{!field f=depositor_ssim}user1@whatever.com"`
```

That is the fancy way of saying: `+has_model_ssim:Collection +depositor_ssim:user1@whatever.com`

Literally I could replace that whole chain of calls with a one-line interpolated string.  The amount of value from abstraction and indirection here is zero.  Instead it decides what query syntax we want to use, that we only want to query `_ssim` fields, and that we wanted a field query with text analysis (i.e. phrases).  Nope, we're asking about strings.  Just strings.  I don't get it.  If you want performance out of your index, then expecting developers to understand rudimentary query syntax should not be a big ask.

Anyway, crux being, we need to be able to ask solr the above question, and the fact that `depositor` happens to be a field we know we can query on is why it was used, not because it answers the question completely.  At least, certainly not from a hybox perspective using groups and permissions.  I'll try implementing `collections` via the existing builder to satisfy the narrow case, but both Sufia on its own and Sufia as part of HyBox will inevitably need to come back to the larger question of permissions indexing, likely soon.

**Comment by atz** [comment]
@cam156 what order would you like the list displayed in?  sorted by title? id? last_updated?  

Might as well have the query establish that order rather than post-sort the list.

**Comment by atz** [comment]
Looks like this part of CurationConcerns is designed to do exactly what we need:
https://github.com/projecthydra/curation_concerns/blob/99b38015bca4bb621c476325978293b755b7f131/app/controllers/concerns/curation_concerns/selects_collections.rb#L33-L37

But seeing as how it is configuring Blacklight, it would have to be used in a Controller.  That is assuming we follow the convention of CC's `access_levels` and `discovery_perm(ission)s`.  Do we?

**Comment by atz** [comment]
Looks like we do at:
https://github.com/projecthydra/sufia/blob/956b0ed3defdd8577f327321aadabbdb64ca5d02/app/search_builders/sufia/my_search_builder_behavior.rb#L8-L15

But then it also triggers the inclusion of advanced search as here:
https://github.com/projectblacklight/blacklight_advanced_search/blob/57b65c7a5c59209fd2fc3f9df1a8748ed1169812/lib/blacklight_advanced_search/advanced_search_builder.rb#L45-L78

**Comment by atz** [comment]
Ok, from logs, I'm seeing an example like (line breaks added):

```json
"fq"=>["
({!terms f=edit_access_group_ssim}public,registered) OR 
({!terms f=discover_access_group_ssim}public,registered) OR 
({!terms f=read_access_group_ssim}public,registered) OR 
edit_access_person_ssim:user80@example.com OR 
discover_access_person_ssim:user80@example.com OR 
read_access_person_ssim:user80@example.com
", 

"{!terms f=has_model_ssim}GenericWork,Collection", 

"({!terms f=edit_access_group_ssim}public,registered) OR 
({!terms f=discover_access_group_ssim}public,registered) OR 
({!terms f=read_access_group_ssim}public,registered) OR 
edit_access_person_ssim:user80@example.com OR 
discover_access_person_ssim:user80@example.com OR 
read_access_person_ssim:user80@example.com
"], ...
"q"=>"{!lucene}_query_:\"{!dismax v=$user_query}\" _query_:\"{!join from=id to=file_set_ids_ssim}{!dismax v=$user_query}\"", 
"defType"=>"dismax", 
"user_query"=>"rocks"
```

Good news: has "groups".  

Bad news: note the same clauses injected multiple times.  We are apparently that literal. I don't mind mixing query syntaxes: that's fine.  But a 6-clause 9-branch block injected twice?  Feels wack.  Are we relying on the `fq` caching to hit *within the same query*?  I'm not sure that it does.  I don't think it will scale to have bespoke cached `fq` per user.  What we really want is the `public,registered` block as it's own, common to all users, but then we would be trying to mix and match `fq` AND operations with OR operations.  

Payoff: we want to use `edit_access_person_ssim` for this particular page list.  And maybe that ugly join query.

**Comment by atz** [comment]
Apparently we can and *do* use the `fq` to do a lucene `!join`, as here:
https://github.com/projecthydra/sufia/blob/master/app/search_builders/collection_search_builder.rb#L11

Two, actually, in the same statement.  That gets rid of the mix/match problem, but having assiduously avoided using Solr joins till now, I have no idea whether the performance implication of a double fq-join in particular is merely bad vs. terrible vs. maybe partially mitigated by fq caching.

**Comment by cam156** [comment]
@atz Sorry I did not comment sooner.  I was out on Friday and working on a security vulnerability yesterday.

I believe we have sorted in update order in the past, but at the work screen we may want to sort alpha.  @mtribone @elrayle do you have an opinion on the order?

I am guessing that the layering of the code created the multiple injection of statements and you are the first to notice.  It could either be another ticket or you could fix it while you are in. @mjgiarlo any opinion?  Are you sure it is the same exact statement.  Sometimes the queries for groups look pretty repetitive.
We definitely want to do groups.  I have always seen that group query the same way since it comes out of Hydra-access-controls.  This group and this group and this  group, with any access level we can have.  I think part of the problem is we do not store the key for read access in solr if the user has edit access even thought that implies read access, so we have to check for users with read access or users with edit access ect. @jcoyne any timing tests done to see if this causes solr slowness?

When we implement the user groups in ScholarSphere using ldap the query changes to include our specific groups, so you may be ok with the LDAPy part for hybox.

**Comment by atz** [comment]
Yes, it is exactly the same.

**Comment by cam156** [comment]
@atz Sounds like you have found a bug.
