### ISSUE TITLE
Temporarily disable workflow approval step(s) for an Admin Set

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#2444]
As an administrative user, I need to be able to configure an approval workflow, with the option to disable the approval step(s) at an Admin Set-level for one-offs.

Requires implementation of Admin Sets.

**Comment by jeremyf** [comment]
Does each Admin Set have its own workflow?

Does this imply that we can disable and enable approval steps?

**Comment by mjgiarlo** [comment]
:arrow_up: @hannahfrost @vantuyls

**Comment by hannahfrost** [comment]
@jeremyf I think approval should be configurable (disable/enable) per admin set, because not every set will necessitate gate-keeping and not every implementor will have staffing to review every work that is added to a set.

I'm less certain about the need to toggle for a one-off (eg, disable, add a work, then re-enable), but it should be possible to at least disable/enable approval after an admin set has been established and populated for those cases that the requirement for review across the set has changed.

**Comment by vantuyls** [comment]
agree with @hannahfrost . 

@jeremyf - i think every admin set gets it's own workflow, even if that workflow is self deposit (ie no workflow).

**Comment by jeremyf** [comment]
@vantuyls Yes. Every admin set should have a workflow.

**Comment by vantuyls** [comment]
Rework this issue to be: If depositing into a workflow and i’m an admin i can optionally shortcut the workflow

**Comment by jeremyf** [comment]
Agreed. Every object has an Admin Set. Self deposit is a simple set.

Jeremy Friesen

**Comment by mjgiarlo** [comment]
We already have a ticket for the reworking suggested by @vantuyls on 9/1, so I'm closing this one.
