### ISSUE TITLE
acts_as_followable no longer maintained

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2485]
We need this PR for Rails 5 support:
https://github.com/tcocca/acts_as_follower/pull/71

However, there have been no commits to the repo in over two years.  We need a plan about how to move forward. Some options may be limited by the fact that the original code is MIT licensed.

**Comment by mjgiarlo** [comment]
It may be worth my checking with Sufia users whether this is a feature anyone cares about.

**Comment by mtribone** [comment]
Not so sure that the following/followers is heavily used.

**Comment by awead** [comment]
Here are some quick stats from Scholarsphere:

Total users: 1466
Total users following or being followed: 21
Point spread: `[1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 9, 9, 11, 17, 29]`

So other than three very "social" users, it's not used that much.

**Comment by cam156** [comment]
Unfortunately our Dean of the Library is one of the users.  We may need to put this back into ScholarSphere.

**Comment by awead** [comment]
It seems like the upcoming admin dashboard might be able to address some of these needs. If one or a few users need to track the activity of other users, that seems like a good feature candidate.

**Comment by mjgiarlo** [comment]
@awead Wow, great data. Thanks for that. Out of curiosity, do you know who the 9, 9, 11, 17, 29 people are? Are they like you, me, Dan, Patricia, Carolyn? :) If it's mostly the dev team, that may be good evidence that this feature isn't widely used.

We should also check how this feature is used in other Sufia implementations. Pinging @pbinkley @afred  @rotated8 @kerchner @scossu @elrayle @jhallida @dbrower

**Comment by mjgiarlo** [comment]
All: see https://github.com/projecthydra/sufia/pull/2539.

**Comment by scossu** [comment]
I mentioned this to our product manager a while ago and she was interested, but we are currently not planning any functionality around the follow feature. However, I must say it always sounds like tough news when a feature is turned off without offering an alternative.  

Is there a current, low-maintenance gem that can replace this feature, or can a workflow be designed that achieves similar results with built-in tools (e.g. notifications)?

**Comment by mjgiarlo** [comment]
If it turns out that few folks are interested in the feature (which, tbh, I shoehorned in way back when, when I was bored on a weekend...), one option that is better than 'everyone should implement this themselves in their apps' is that a new gem could be made out of this code by said folks as a sufia plugin of sorts.

**Comment by dbrower** [comment]
We are not using it in our sufia app. In fact we ripped out most of the user profile routes.

**Comment by rotated8** [comment]
While we haven't touched the feature directly, we did restrict user profile routes to make it almost impossible to use in VTechData. It has not been a selling point for our other (in-development) Sufia heads, either.

**Comment by mjgiarlo** [comment]
@pbinkley @kerchner @elrayle @jhallida ? Any thoughts on this?

**Comment by mjgiarlo** [comment]
@awead: Do you know who the 9, 9, 11, 17, 29 people are?

**Comment by mjgiarlo** [comment]
I'm not hearing many folks stand up for keeping this feature. At this point, I would defer to the Penn Staters and how they would feel about, e.g., moving this implementation into ScholarSphere directly or into a plugin gem.

**Comment by elrayle** [comment]
Sorry for the late response, I didn't see this until it was on the hydra-tech agenda today.  Must have got lost in email.

We were considering using this with an upcoming project.  We are planning to add code to manage subscriptions for recurring releases of a title.  We were going to look at the follower code to see if any of it could be leveraged.  We are also looking at other possibilities.  Too early for me to make a firm statement about whether the follower code is critical to this effort.  I suspect it would not be sufficient and we would be looking elsewhere.  But that is just intuition speaking.

**Comment by awead** [comment]
@mjgiarlo if Penn State volunteered to maintain it, would that be an acceptable solution? That is, if we at Penn State feel it needs to remain in Sufia. I think we're presently figuring that out right now, but it's going to take more than a week or two. If we decide after that time that we don't need to offer it any more as a feature in Scholarsphere, then we can go ahead and remove it from Sufia.

So the questions now are:

1. What needs to happen now in order to keep the status quo while we figure all this stuff out?
2. Are we (Penn State) willing to maintain this? @cam156 ?

We'd either support the gem and keep the feature as-is in Sufia, or remove the gem and re-write the feature in Scholarsphere. I'm not sure which one is more work. The former would have community benefit, if there are others who still need this.

Door Number Three: remove the gem and re-implement the feature in Sufia without it or using a different gem.

**Comment by mjgiarlo** [comment]
@awead As long as @cbeer is OK having his PR hang out there a while, I think the answer to (1) is that nothing needs to happen to maintain the status quo. I don't need to force the issue in the next week if @cbeer is comfortable with having to rebase his branch in a couple weeks when things settle at Penn State.

I really don't want to open door number three if we can avoid it, but thanks for adding that as an option to consider. :)

**Comment by awead** [comment]
@mjgiarlo agreed. I just don't know how long it's going to take for Penn State to figure out our answer. We're actively working on it, though. And by _we_, I mean people other than me.

**Comment by hackmastera** [comment]
Okay we are using it here as a tool in metadata QA. Being able to see what's recently updated is the only way to know which records to review. The workaround would be visiting each user's profile to see the recent updates there. We don't have very many users so that may work for us. Putting this on our team meeting agenda for a week from now.

Maybe the functionality under development by the workflow folks will obviate our use case? I'm not exactly sure.

**Comment by awead** [comment]
@hackmastera interesting use case! Yeah, I think you could get the same feature differently, if you just need to see what's been recently updated. That could be solved in the admin dashboard feature. It seems like others are using this feature in various ways that we should keep it around for the interim, but that ultimately, it could be removed and replaced with some else more maintainable.

**Comment by mjgiarlo** [comment]
@hackmastera Thanks! I suspect the mediated deposit sprints may bring about another implementation of what you need. In the meantime, do you have any user stories or use cases written up about CHF's needs here? It'd be good to see them.

**Comment by cam156** [comment]
@mjgiarlo we verified that even the users who have followers and are following people are not actually using the feature.  My guess is they configured poeple and forgot about it.  PSU is good to go for the removal.

**Comment by mjgiarlo** [comment]
Discussed with @hackmastera today and she gave the go-ahead to merge @cbeer's PR.

Thanks, all! If someone does have need of this feature in the future and is inclined to take on maintenance of acts_as_followable, we can always restore the feature later.
