### ISSUE TITLE
A public user should see a list of admin sets so they can see which sets are in the repository

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2501]
- [ ] The header should have a link to "admin sets" (text should be i18n)
- [ ] When you follow the link you see a list of admin sets
- [ ] When you click on each admin set you should go to the admin set show page. (#2502)

An admin set is discoverable to a public user when:
- it contains at least one publicly visible work
- it contains required metadata for the set (title, description, language, etc.)
- the public user has permissions to discover the admin set

**Comment by jcoyne** [comment]
Since this ticket depends on #2502, which is design needed, I think this ticket is blocked and also needs design.

**Comment by jcoyne** [comment]
Design question: how do we get here?

**Comment by atz** [comment]
This is a regular user in the context of discovery/browse.

**Comment by ggeisler** [comment]
### Link on home page

The mockup below includes a link to the list of admin sets from the home page (rather than adding a link in the site header, this mockup assumes admin sets will be featured in some way in the main content area. The link "View all admin sets" is the link the user clicks to see a list of admin sets. The details of how this link is shown on the home page will probably change at some point when this aspect is more thought out.)

I'm not sure we've settled on the label we want to use for "Administrative Set." I used "Administration Collection" for the visitor-facing pages here, but we might change that later.

![visitor-home](https://cloud.githubusercontent.com/assets/101482/18104693/300c3040-6eb1-11e6-82ef-aa6b7bda912d.png)

--
### List of admin sets

The list page offers both a list view and a gallery view. In the list view, I propose showing a short excerpt of the work description under the title in the list of works section. But I think we want this to be only a line or two, so we'll need to truncate based on length. We can figure out the best length at which to truncate after seeing the page in action.

#### List view
![visitor-list-list-view](https://cloud.githubusercontent.com/assets/101482/18104724/51cc5cb4-6eb1-11e6-8187-c23beae689c1.png)

--
#### Gallery view
![visitor-list-gallery-view](https://cloud.githubusercontent.com/assets/101482/18104732/5817dff8-6eb1-11e6-8be3-708efe95730b.png)

**Comment by hackmastera** [comment]
Which will be the default: list view or gallery view? This may be the sort of thing people would want a setter for.

**Comment by jcoyne** [comment]
@hackmastera That would be a blacklight concern.
