### ISSUE TITLE
On the item ingest page, as an admin, I should have a button that bypasses the review workflow

### ISSUE THREAD

**Issue by straleyb** [projecthydra/sufia#2634]
When logged in as an administrator, a user should be given a button to save and review. Instead of save and add to review queue.

**Comment by mjgiarlo** [comment]
Perhaps a button like GitHub's merge button which provides two choices (merge commit or squash merge)?

**Comment by hortongn** [comment]
@vantuyls @mjgiarlo I think I've resolved this issue with #2617.  In my #2617 if an admin creates a new work, the form has radio buttons to save the new work as active or inactive (defaults to inactive).  So this effectively allows an admin to by bypass the review process by saving a new work as active (approved) if they choose.  

What do you think?

**Comment by mjgiarlo** [comment]
Hi, @hortongn. Do only admins see the new button?

**Comment by mjgiarlo** [comment]
Tagging @jeremyf @elrayle for comment, as we discussed this in the context of CC's inclusion of Sipity workflows.

**Comment by elrayle** [comment]
A configuration that allows actions based on roles could be configured to add an action that allows an **admin** to go straight from **new_state** to **published_state**; while other users with none-admin roles have many other steps between.

This will work with simple workflows that limit actions to those available in the New Work UI.

If you have a more complex workflow where one step is an **external metadata enhancement** state, you would not want to jump from **new_state** to **published_state** because the enhancement would never happen.  The jump is not a play through all states.  It is a jump that skips the normal in-between states.

**Comment by mjgiarlo** [comment]
Defer this ticket until we have working 1+-step workflow.
