### ISSUE TITLE
Work's show view should error when object is in mediated deposit inactive state.

### ISSUE THREAD

**Issue by blancoj** [projecthydra/sufia#2727]
When mediated deposit is enabled, and a work is in inactive state because it is in the mediated deposit workflow and has not yet been approved, the work’s show views should error, regardless of the visibility specified.

What that error looks like is important. A discussion of that needs to take place.

**Comment by jcoyne** [comment]
Why should there be an error?

**Comment by vantuyls** [comment]
i think this is less of an error than a friendly "you can't do that" page

**Comment by mjgiarlo** [comment]
Is this mediated deposit-centric behavior, or does the digitization workflow use case also want similar behavior? The key question is: "what does the show page of an object that's not all the way through its workflow look like? does this depend on what your roles in the system are?" Changing this to a question ticket, and asking @ggeisler to sound off.

**Comment by ggeisler** [comment]
Prevent the user from getting to the show page of an unapproved item? Show an alert modal with text like "This work is not currently viewable because it has not yet completed the approval process." and just provide a "Close" button to dismiss the modal and put them back where they were when they tried to go to the unapproved item page?

Otherwise, if you have to display the show page, I think you'd just show an empty page with a message telling the user why the page is empty. Something like:

![a_test_work](https://cloud.githubusercontent.com/assets/101482/19824705/b1b51974-9d26-11e6-8a10-c19b9b8329cb.png)

But you'd also need to provide a way back to where they were, since this page is not useful to them, so using a modal to prevent them from getting here in the first place seems preferable.

**Comment by mjgiarlo** [comment]
@luisgreg99 per @tpendragon:
> [It's OK to put this PR in CC] As long as it depends on what your role is.
> 
> Hiding the show view always seems silly, but if you don’t have permission to see incomplete items..
> 
> So I guess if the ticket is “As an anonymous user, I shouldn’t be able to see items which haven’t reached the viewable portion of their workflow"
