### ISSUE TITLE
Set default workflow for Generic Work in Sufia

### ISSUE THREAD

**Issue by vantuyls** [projecthydra/sufia#2807]
The "off the shelf" Sufia should have a default workflow built in for Generic Works when one spins the thing up for the first time and turns on Workflows. That default workflow should mimic the behavior of Sufia deposit when workflow is turned off (self deposit, no mediation or need for approval).

**Comment by mjgiarlo** [comment]
Sufia doesn't come pre-baked with GenericWorks anymore. Sufia should have a default workflow that applies automatically to the first and any subsequent curation concerns that are created.

**Comment by jcoyne** [comment]
I believe this is taken care of by projecthydra/curation_concerns#1035

**Comment by scholarworks** [comment]
2 questions:

1 - there remains a "generic_work" type in sufia, and when adding a work, there are then 2 work types (work and generic_work) as well as 2 "Create a work" links. Is this because of including the workflow branch of cc, or because of the timing of mediated_deposit_epic, which may need to be cleaned up?

2 - When creating a work, a generic workflow is created in the config directory, though I think it's probably more complex than what we would want as a "Default". I'm happy to jump into cleaning that up, would it be in a generator?

**Comment by scholarworks** [comment]
Agreed with @jcoyne that it may be handled by cc #1031, but we may want to discuss if we want anything  different before closing.

**Comment by mjgiarlo** [comment]
@scholarworks 

1. Where are you seeing this `GenericWork` type? Sufia doesn't ship with any default work types, but we **do** create a `GenericWork` when we build the test app (because we need to test with a model).

2. I defer to @jcoyne and @jeremyf on that one.

Thanks!

**Comment by scholarworks** [comment]
@mjgiarlo - Yeah, this is in the test app, a GenericWork is in place and a generic_work_workflow.json is in .internal_test_app/config/workflows/ initially.

When a Work is added, a work_workflow.json is added.

I added a workflow.json.erb at sufia/lib/generators/curation_concerns/work/templates but it isn't getting picked up, so I'm assuming this isn't sufficient to override the one already in CC.

Thanks.

**Comment by mjgiarlo** [comment]
![2016-10-25 14 55 39](https://cloud.githubusercontent.com/assets/131982/19705884/e369fc56-9ac3-11e6-9909-5aeba2b49e82.jpg)

**Comment by vantuyls** [comment]
Closing this in favor of resolving the issue through Curation Concerns issues #1031 and #1035
