### ISSUE TITLE
When you start a batch create you should be prompted for work type

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#2913]
When you click "Works" -> "Batch Create"  a modal should pop up offering you a choice of which type of work to create.  This should be similar to when you choose "Works" -> "New Work"

**Comment by atz** [comment]
Specifically, we mean the `Resource type` select box, right?

**Comment by jcoyne** [comment]
@atz I talked with @mjgiarlo about this a few weeks back. He said no, not the "Resource type".  It's supposed to be the modal that pops up (same one as when you specify create a work)

**Comment by atz** [comment]
@jcoyne: to rephrase my question, specifically we mean the modal pop up should be "similar to" (i.e. contain exactly the same possible value(s) and semantics) as the `Resource type` select box on the "New Works" page, right?  If it is NOT the Resource type you were comparing to, then please specify.

**Comment by atz** [comment]
That seems to correspond to `app/views/records/edit_fields/_resource_type.html.erb`:
```
<%= f.input :resource_type, as: :select, collection: ResourceTypesService.select_options,
    input_html: { class: 'form-control', multiple: true } %>
```

**Comment by mjgiarlo** [comment]
No, we're talking not about the values that are among the resource types; they are the curation concerns that have thus far been generated and registered. So, in Hyku, there'd be two: Generic Work and Image.

**Comment by atz** [comment]
Why is this a Sufia ticket then?

**Comment by mjgiarlo** [comment]
@atz Good question. Because the batch create upload workflow only exists in Sufia.

**Comment by atz** [comment]
That is an argument for not putting it at a lower level than Sufia.  But I don't see why this isn't in Hyku.  What does this feature do for a non-Hyku consumer?  Where do the values come from for them?  If the values come from Hyku, how can Sufia code be expected to reference that?

Back to my original question: @jcoyne's comparison (`This should be similar to when you choose "Works" -> "New Work"`) is to something in Sufia or something in Hyku?  Having ruled out `Resource Type`, I see nothing in Sufia's "New Work" page that I recognize as fulfilling this function.

**Comment by atz** [comment]
Critical context: this is only visible after you generate additional work type(s).  Something like:
```bash
rails generate sufia:work image title:string description:string ...
```

**Comment by atz** [comment]
After tracing how things are built now, trying to extend the current pattern for models to batches of the same suggests needing new models for the batch-variants (i.e. `BatchGenericWork`, `BatchImage`).  That seems lame.

I’m not sure how to workaround the presenter stuff elegantly, and how much would be considered acceptable.  We can’t reuse the modal form w/o changing the destination of the links, and that is currently controlled by presenters inside a **SelectTypeListPresenter**'s `create_work_presenter.each` loop.  Adding model/presenter classes seems misguided since "batchness" is an orthogonal quality that will be shared by all models. I would hate to then find another such boolean quality `foo` and end up adding additional dimensions to a matrix that requires `FooGenericWork`, `BatchFooGenericWork`, etc. for each generated model.

Makes me think the presenters (or at least `SelectTypePresenter`) should take an argument (or have a settable attribute) for “batch or not”.

The modal is pre-rendered hidden already, so it's logic is completely inflexible to reuse.  The modal template could become batch-aware by:
- Copy it, surgically alter links/DOM ids, and render *both* modals hidden. This is copy/pasta and adds to a bad pattern.  I want to avoid that.  
- Make it more abstract and render on demand, either by client side JS template or server request.  Downsides: accessibility(?) or latency, respectively.  Upsides: less bloat, more reusable.
- Expanding it to offer (when applicable) both batch and non-batch links.  Upsides: does not change current hidden-render pattern, achieves 1 degree of reuse.  Downsides: same; even *less* open to further reuse; requires some changes underneath.  

My current inclination is to have modal differentiate between “add one” and “add batch” for each model, and remove “Batch Create” from the toolbar altogether (or remove it from doing anything different than call up the same modal that "Add Work" does).  Is that an acceptable alteration to design? If not, we need to determine the scope of changes in play.

@jcoyne, @cbeer, @mjgiarlo: interested in your thoughts here.

**Comment by atz** [comment]
I have wired in the modal to look like:
![screen shot 2016-12-12 at 3 46 01 pm](https://cloud.githubusercontent.com/assets/109954/21121581/3221d808-c082-11e6-8af1-764c651abf33.png)

Perhaps we will want to abandon (or augment) the existing "single work" links in favor of comparable buttons, for consistency.  But I am deferring styling cleanup for whenever the modal can get more love from a designer.  Note: icons defaulty, etc.

Given what we have already, the operation we’d need to do is something like setting the `@_model_name` inside the `Sufia::Forms::BatchUploadForm` instance, overriding this: https://github.com/projecthydra/sufia/blob/master/app/forms/sufia/forms/batch_upload_form.rb#L31

The blocker now is that CurationConcerns wants to be entirely class (name) driven.  We only get to provide the class name in `BatchUploadsControllerBehavior`.  That is how it decides to render the batch uploads form.  I don’t know how to workaround that, i.e. intercept CurationConcerns’ call of `Sufia::Forms::BatchUploadForm.new`

We could minimally extend `Sufia::Forms::BatchUploadForm` with another class and do the setting in that initializer, but that requires:
- a new `Sufia::BatchUploadsControllerBehavior::BatchUploadFormService` per object type, and 
- a new `Sufia::BatchUploadsControllerBehavior` per object type, and
- a new `Sufia::BatchUploadsController` per object type...

Those would need to be generated with the other model files.   I don’t much like that approach.  Total overkill for the problem of needing to pass one parameter into the form level.  The alternatives are metaprogramming magic, refactoring CC's brain around this feature, and **???**.

**Comment by atz** [comment]
The text of the "Batch Create" buttons is from `t('sufia.toolbar.works.batch')` and the links are to: 
- http://localhost:3000/batch_uploads/new?concern=Imago
- http://localhost:3000/batch_uploads/new?concern=GenericWork
- etc.

The problem is (as described above), how to handle that param on the back end.

**Comment by atz** [comment]
I suppose we should also be filtering for the current_user's ability to create the concerns in question, rather than showing links that might fail when attempted.  Notably, the old single-work interface didn't yet do that.  @mjgiarlo, please determine whether you want to deal with that here or defer it.

**Comment by jcoyne** [comment]
@atz Can you adjust `BatchUploadFormService` https://github.com/projecthydra/sufia/blob/cc6cf29c51ec8b52c7220065e20f7b5fc5c292b8/app/controllers/concerns/sufia/batch_uploads_controller_behavior.rb#L20 to give you an instance of `BatchUploadForm` with the model set?

**Comment by atz** [comment]
@jcoyne No, I don't think so.  The class method returns a class name (as per Curation Concerns API).  It is not a constructor.  That's why I said: 

> I don’t know how to workaround that, i.e. intercept CurationConcerns’ call of `Sufia::Forms::BatchUploadForm.new`.  

We can override the `form` method (caching constructor) here:
https://github.com/projecthydra/curation_concerns/blob/master/app/controllers/concerns/curation_concerns/collections_controller_behavior.rb#L217

but that method doesn't receive any parameter, so it doesn't give us flexibility for multiple concerns.

In the end, we specify a class so that we can have a class method (with an unused argument? that is the concern?) that returns a different class name.  Seems like a lot of runaround.  We need that argument passed to the `form` method and we could bypass the rest of that noise.

**Comment by atz** [comment]
Notably, if we're going to override both methods, we might as well just not inherit from `WorkFormService`, since that is literally all the class is.

**Comment by jcoyne** [comment]
Yeah, if that doesn't make sense, then throw it out.  We just need to make the functionality work, the mechanism is of no value.

**Comment by atz** [comment]
OK, the next problem I see is timing. This module needs to know the concern/model at **include** time: https://github.com/projecthydra/sufia/blob/cc6cf29c51ec8b52c7220065e20f7b5fc5c292b8/app/controllers/concerns/sufia/batch_uploads_controller_behavior.rb#L9

In a rails Controller, include time is per session, and we want this behavior to vary per **request**.  

And that assignment does all kinds of side-effect stuff important to Sufia and CC layers:
https://github.com/projecthydra/sufia/blob/cc6cf29c51ec8b52c7220065e20f7b5fc5c292b8/app/controllers/concerns/sufia/works_controller_behavior.rb#L14-L17

Seems like at a minimum we need to convert those `before_action` side-effects to use a clause like:
```ruby
unless: -> { curation_concern_type.nil? }
```
*outside* the method.  OK?

**Comment by atz** [comment]
Hmm... we would also need to unset the class variable at the end.  Really feels like all the in-mixing and module/class-level variables is the wrong pattern here.

**Comment by atz** [comment]
The main failure of our Sufia approach to “batching” of CurationConcerns concerns is that a CC Controller expects you set at the **class** level the `curation_concerns_type` and that assignment side effects the controller by calling CanCan’s `load_and_authorize_resource`.

https://github.com/projecthydra/curation_concerns/blob/master/app/controllers/concerns/curation_concerns/curation_concern_controller.rb#L23-L26 

`l_a_a_r` then adds its own before filter: https://github.com/ryanb/cancan/blob/4560928dc375f9b31de00381c98334eb6aabc4b9/lib/cancan/controller_additions.rb#L15 (edited)

So we cannot reuse the same controller for multiple types without doing per-request surgery on the `before_action` filters, because the old type's filter will not be helpful.  I know "reuse this form again for batches" seems like a simple ask, but if you want to follow CurationConcerns architecture here, it isn't.  So again, I need somebody to decide how much is in scope.

**Comment by atz** [comment]
Another sufia question: the rails convention is that `XyzController` is for `Xyz` objects.  But `Sufia::BatchUploadsController` is for… `Sufia::BatchUploadItem` objects?  I get that we're using that class as a null model stand-in, since we don't actually intend to persist it, but I don't see that as a reason for deviating from convention.

**Comment by mjgiarlo** [comment]
While you're making changes, feel free to more closely align our batch upload code with Rails conventions, @atz. Good call.
