### ISSUE TITLE
File manager should have optimistic locking version

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#3055]
Given that this would require changes to javascript in CurationConcerns, to reference attributes only in Sufia, I'd prefer we do this in Hyrax.  

cc @hackmastera @mjgiarlo @tpendragon

**Comment by hackmastera** [comment]
alternative would be to move work from the sufia pr over to cc.

Can someone also tag other sufia 7.3 people? The Cincinnati crew? PSU? I'm
interested in how important this is to them. How long do people anticipate
being on sufia?

**Comment by mjgiarlo** [comment]
@awead @cam156 @hortongn @scherztc @weiweishi @grosscol see :arrow_up: Related to #3046.

**Comment by cam156** [comment]
@mjgiarlo, @jcoyne & @hackmastera The ticket does not give any details.  I'm at a loss as to how to interpret it.  What error is it trying to fix?

**Comment by hackmastera** [comment]
@cam156, currently in sufia 7.3 if two processes / people edit a work at the same time, the second overwrites the first. The scenario we're seeing at CHF is that a depositor uploads their multi-file work, then immediately edits metadata with the edit form or changes its thumbnail with the file manager. Because the filesets are added to the work as background jobs, those continue to process as the form is open. Then when the form is saved, work/file relationships created while the form was open are lost without the user's knowldge.

There's a PR to fix the edit form, but extending it to the file manager (for changing thumbnails and ordering files) will require doing some work in curation concerns.

**Comment by cam156** [comment]
@hackmastera we discussed this issue on Friday locally.  We discussed just locking the file while the uploads were in progress, but that would not solve two people editing the file.  Can you point me at the fix for the form? @awead mat want to back port that to ScholarSphere.

**Comment by hackmastera** [comment]
@cam156 Here's the PR that fixes the edit form https://github.com/projecthydra/sufia/pull/3054

I could move the work over to cc if @jcoyne doesn't have time to so that we could fix this for the file manager as well.

**Comment by jcoyne** [comment]
@hackmastera I have a cc or almost done
