### ISSUE TITLE
Upgrade install template for 7.3.0.rc1

### ISSUE THREAD

**Issue by elrayle** [projecthydra/sufia#3075]
### Descriptive summary

The installation template for creating a new Sufia app needs to be updated to use the 7.3.0.rc1 release.

### Expected behavior

Creating a new app with template.rb should use the latest 7.3.0.rc1 Sufia gem.

### Actual behavior

Creating a new app with template.rb uses 7.2.0 Sufia gem.

### Steps to reproduce the behavior

1. run `rails new my_app -m https://raw.githubusercontent.com/projecthydra/sufia/master/template.rb` in terminal to create a new Sufia app.

### Possible solutions

Option 1:
* replace current contents of https://raw.githubusercontent.com/projecthydra/sufia/master/template.rb with the contents of gist https://gist.github.com/elrayle/2c26ff82145e6374cc7eed768c742b9b

Option 2:
* create a separate template file for each major release
** https://raw.githubusercontent.com/projecthydra/sufia/master/template.rb   # has latest full release
** https://raw.githubusercontent.com/projecthydra/sufia/master/template_7.2.0.rb 
** https://raw.githubusercontent.com/projecthydra/sufia/master/template_7.3.0.rc1.rb

This would allow a user to choose which version of Sufia to use.

**Comment by jcoyne** [comment]
I'm not sure we should update the template with a release candidate.  Can we wait until we have a final release?

**Comment by mjgiarlo** [comment]
@elrayle I'm not inclined to make major changes to this in Sufia with the possibly final (7.3.0) release coming soon. (And we have a related pending PR here: https://github.com/projecthydra/sufia/pull/3071/files#diff-281a446193b96436f21d35a03e1fa073)

That said @projecthydra/sufia-code-reviewers @elrayle @jcoyne, how do you think we should handle this in Hyrax going forward? I ask because Justin and I went back and forth on this for quite some time last week, with the two options being:

1. README always points at the template in the `master` branch, and the template is updated with each release to point at the latest release. This means that the README will always install the latest stable release of Hyrax.
1. README always points at the template corresponding to the current release. So if you're reading the README for Hyrax 1.2.0, you get Hyrax 1.2.0 installed. If you're reading the README for 0.1.0, you get 0.1.0 installed. If you're reading the README in master, you get the latest stable release of Hyrax.

I'd welcome folks' thoughts on this.

**Comment by mjgiarlo** [comment]
See also some past discussion here: https://github.com/projecthydra/sufia/pull/2783#pullrequestreview-3965724

**Comment by mjgiarlo** [comment]
Replaced with https://github.com/projecthydra-labs/hyrax/issues/492.
