### ISSUE TITLE
"Select current page" broken in My Works

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#3082]
If I have multiple works and I'm looking at the My Works view, there is a cog icon that, when clicked, should allow me to select all works currently visible via "Select current page". It has no apparent effect.

Discovered this after 7.2.0 :arrow_right: 7.3.0.rc1 upgrade.

**Comment by hortongn** [comment]
So instead of showing both the checkbox and the cog with dropdown in the column header, we probably want a simpler or more integrated solution.  A couple of suggestions are below.  Would appreciate some input from folks.

1) Use only the checkbox in the header.  Clicking the box checks all of them and clicking it again clears all of boxes.  I think generally people understand this approach.

![checkbox](https://cloud.githubusercontent.com/assets/5639859/23108396/c3c98a2e-f6da-11e6-99e0-ee9649af3215.png)

2) Use a checkbox in the header like above, but also include a little dropdown indicator that shows a All/None menu.  Clicking directly on the checkbox or using the menu has the same effect. People just have a choice of how they want to do it.

![checkbox-dropdown](https://cloud.githubusercontent.com/assets/5639859/23108443/62a61176-f6db-11e6-9259-6be899b76cd4.png)

Thoughts or other suggestions?

**Comment by jcoyne** [comment]
I like the drop down option. This is similar to how gmail does it
