### ISSUE TITLE
geonames API should have username.

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#827]
Currently the response is returning:
```
401 Unauthorized
{"status":{"message":"Please add a username to each call in order for geonames to be able to identify the calling application and count the credits usage.","value":10}}
```

**Comment by tonmoy18** [comment]
Is this issue still relevant? We do not seem to be getting such 401 response at present.

**Comment by hackmastera** [comment]
Username was added as a configurable value in 6.4. But edit_metadata.js needs to be changed to query '/authorities/geonames/location' instead of querying the API directly. Also it would be nice to namespace the code in edit_metadata.js. I thought there was another ticket for moving geonames to questioning authority but i can't find it now.

**Comment by mjgiarlo** [comment]
@hackmastera I don't see an issue for that, @hackmastera. I'm inclined to close this issue and encourage you to put in issues for the stuff you mentioned. Is that :ok_hand:?

**Comment by Code4SAFrankie** [comment]
Might want to add this to the error message: Where does one get a username? Is this a paid for service?
