### ISSUE TITLE
Unnecessary change to date_modified

### ISSUE THREAD

**Issue by awead** [projecthydra/sufia#870]
Is this needed?

https://github.com/projecthydra/sufia/blob/master/app/controllers/concerns/sufia/batch_edits_controller_behavior.rb#L51

Is it updating the generic file or the batch object?

**Comment by mjgiarlo** [comment]
I don't see this method called anywhere in the sufia or scholarsphere codebases FWIW.

**Comment by mjgiarlo** [comment]
OK, I take back that last comment -- this method overrides one provided by hydra-batch-edit:

https://github.com/projecthydra-labs/hydra-batch-edit/blob/master/app/controllers/concerns/hydra/batch_edit_behavior.rb#L31-L34

I believe this is editing each GF, because I don't believe HBE is aware of the notion of batches in Sufia.

**Comment by awead** [comment]
@mjgiarlo I was questioning the legitimacy of that line of code... I thought that the actor should handle that, if it was related to GF... if it's on the Batch, though, then fine

**Comment by mjgiarlo** [comment]
That line of code is pre-actor, so it could be we just missed it.

**Comment by awead** [comment]
We can fix this in #928 for 6.1.
