### ISSUE TITLE
Meta: Documentation before 6.0.0 release

### ISSUE THREAD

**Issue by cudevmaxwell** [projecthydra/sufia#880]
It would be immensely helpful to everyone outside the contributors group if the installation of a production ready Sufia instance (on your preferred linux distro) could be thoroughly documented. 

As a naive user blindly following the readme I got as far as an incorrectly configured Solr instance. 

In contrast, I was able to get DSpace up and running in a few hours using their excellent documentation: https://wiki.duraspace.org/display/DSDOC5x/Installing+DSpace

**Comment by jcoyne** [comment]
@cudevmaxwell Does this work for you: https://github.com/curationexperts/hydradam/wiki/Production-Installation%3A-Overview

**Comment by jcoyne** [comment]
@cudevmaxwell please keep in mind that this is an open source project and your contributions to the documentation would be greatly appreciated.

**Comment by cudevmaxwell** [comment]
I'm happy to help where I can. For example, I'm hoping that a working [vagrant box](https://github.com/cudevmaxwell/sufia-ready-vagrant) will be helpful in the future. 

I just wanted to point out that, as someone new to the project (and hydra in general), the lack of easy to find docs can be an issue for adoption.

The linked documentation will be a helpful starting point.  `s/hydradams/sufia/g`?

**Comment by mjgiarlo** [comment]
Thanks for writing, @cudevmaxwell. I think we've all got different documentation at our own institutions. Part of this is the difference between DSpace as a product and Sufia as an engine for building other, possibly wildly different products. Part is also the speed at which Sufia moves, which makes it all too easy for documentation (especially geared towards production instances) to lag behind.

A working, maintained vagrant box would go a long way! We don't have that at the moment because I don't think any of us with production instances depend upon vagrant at the moment.

Our documentation could absolutely be better, though, so I'm glad you wrote about this!

**Comment by mjgiarlo** [comment]
@cudevmaxwell Oh, and HydraDAM is an implementation of Sufia at WGBH, though it's running an older version than you've got.  So you will doubtless need to make modifications.  Remind me: what version of Sufia are you using?

**Comment by cudevmaxwell** [comment]
Just a clone of master from this afternon. So, basically 6.0.0 rc2.

**Comment by mjgiarlo** [comment]
OK.  Great.  That's definitely way ahead of HydraDAM, but I'm glad to hear you're using the latest and greatest.

**Comment by mjgiarlo** [comment]
Thanks for the feedback, @cudevmaxwell
